### ISSUE TITLE
module 'fix_yahoo_finance' has no attribute 'pdr_override'

### ISSUE THREAD

**Issue by mmehrle** [ranaroussi/fix-yahoo-finance#34]
I am trying to suppress the deprecation warnings with `yf.pdr_override` but am getting this:

>     yf.pdr_override()
> AttributeError: module 'fix_yahoo_finance' has no attribute 'pdr_override'

Also attempted to suppress the warnings myself but without avail.

**Comment by manan904** [comment]
pdr_override was added in the 0.0.18 version of this package...

Run the following code on your terminal and then use the pdr_override code as written in the documentation:
`pip install fix_yahoo_finance --upgrade`

It will upgrade your package to 0.0.19 which is the latest version as of today.

**Comment by mmehrle** [comment]
I'm actually using the direct method and after updateing to 0.0.19 it 
got worse as I am now unable to suppress the warning:

Downloading daily AMZN between 20170701 and 20170912:
     Auto-overriding of pandas_datareader's get_data_yahoo() is 
deprecated and no longer available.
     Use pdr_override() to explicitly override it.
   DeprecationWarning)
[*********************100%***********************]  1 of 1 downloaded

Quite a pain - can that please be fixed?

**Comment by manan904** [comment]
@mmehrle You need to use pdr_override() to remove the warning. Please read the documentation and follow the steps.

Use the following code exactly as it is written below:-

```
from pandas_datareader import data as pdr
import fix_yahoo_finance as yf
yf.pdr_override()
data = pdr.get_data_yahoo("AMZN", start="2017-01-01", end="2017-09-12")
```

You'll see the warning message when you first run these lines but it's just a message that'll disappear once you run these lines of code once again.Your code will run just fine,the warning message will not stop your code from running.

**Comment by bushrang3r** [comment]
I ran each of these snippets as you said.

**from pandas_datareader import data as pdr**
> from pandas_datareader import data as pdr
Traceback (most recent call last):                                                                                                                                          
  File "<stdin>", line 1, in <module>                                                                                                                                       
  File "/usr/lib/python3.4/site-packages/pandas_datareader/__init__.py", line 3, in <module>                                                                                
    from .data import (get_components_yahoo, get_data_famafrench, get_data_google, get_data_yahoo, get_data_enigma,  # noqa                                                 
  File "/usr/lib/python3.4/site-packages/pandas_datareader/data.py", line 7, in <module>                                                                                    
    from pandas_datareader.google.daily import GoogleDailyReader                                                                                                            
  File "/usr/lib/python3.4/site-packages/pandas_datareader/google/daily.py", line 1, in <module>                                                                            
    from pandas_datareader.base import _DailyBaseReader
  File "/usr/lib/python3.4/site-packages/pandas_datareader/base.py", line 3, in <module>
    import numpy as np
  File "/usr/lib64/python3.4/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib64/python3.4/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib64/python3.4/site-packages/numpy/lib/__init__.py", line 17, in <module>
    from . import scimath as emath
**ImportError: cannot import name 'scimath'**

**import fix_yahoo_finance as yf**
> import fix_yahoo_finance as yf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/fix_yahoo_finance/__init__.py", line 29, in <module>
    import numpy as np
  File "/usr/lib64/python3.4/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib64/python3.4/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib64/python3.4/site-packages/numpy/lib/__init__.py", line 17, in <module>
    from . import scimath as emath
**ImportError: cannot import name 'scimath'**

Seems to be a problem with scimath.  Any suggestions?
